name: Release Charts

on:
  push:
    branches:
      - main     # or your default branch
    paths:
      - charts/**/*
      - .github/workflows/chart-release.yaml

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
